version: '2'

services:

  api:
    build: ./bship-api/api
    command: sbt "project bship-api" "~run 8010"
    ports:
      - "8010:8010"
    volumes:
      - ./bship-api:/app
      - ./bship-api/.sbt:/root/.sbt
      - ./bship-api/.ivy2:/root/.ivy2
      - ./bship-api/.m2:/root/.m2
    environment:
      - NICK_NAME=my nick name
      - FULL_NAME=my full name
      - HOST=127.0.0.1
      - PORT=8010
    stdin_open: true

  web:
    build: ./bship-web
    command: gulp serve
    ports:
      - "8020:8020"
    stdin_open: true