version: '2'

services:

  api:
    build: ./bship-api/api
    command: sbt "project battleship-api" "run 8010"
    ports:
      - "8010:8010"
    volumes:
      - ./:/app
      - .sbt:/root/.sbt
      - .ivy2:/root/.ivy2
      - .m2:/root/.m2
    environment:
      - USER_ID=my user name
      - FULL_NAME=my full name
      - IP_ADDRESS=127.0.0.1
      - IP_PORT=8010
    stdin_open: true

  web:
    build: ./bship-web
    command: gulp serve
    ports:
      - "8020:8020"
    stdin_open: true