version: '2'

services:

  api:
    build: ./api
    command: sbt "project battleship-api" "run 8010"
    ports:
      - "8010:8010"
    volumes:
      - ./:/app
      - .sbt:/root/.sbt
      - .ivy2:/root/.ivy2
      - .m2:/root/.m2
    stdin_open: true